{*******************************************************************************
*                                                                              *
*                          OPCODE DEFINITION MODULE                            *
*                                                                              *
*                       Copyright (C) 2006 S. A. Moore                         *
*                            All rights reserved                               *
*                                                                              *
* PURPOSE:                                                                     *
*                                                                              *
* Defines the opcodes for this assembler module.                               *
*                                                                              *
* WARNING: *** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY ***         *
*                                                                              *
* This file is generated by hastab from the input file opcode.lab. It defines  *
* the opcodet type, which is an enumerated list of all opcodesin use,          *
* including the assembler directives in use.                                   *
*                                                                              *
* CREATING:                                                                    *
*                                                                              *
* To create this file, run hashtab in this directory.                          *
*                                                                              *
*******************************************************************************}

module opcdef;

{ Opcode type.

  Note: the entries opnull and oplast mark the start and end of the table,
        respectively, and don't represent actual opcodes. }

type  opcodet = (opnull,opdec,opinirw,opaddw,ophalt,oprlca,opdecw,
                 opdjnz,opdivuw,oplddr,opinc,oprrca,opcpdr,opsla,
                 opldir,opretn,opindr,opcpir,opmultw,opdaa,opincw,
                 opinir,opadd,opreti,opldup,opccf,opiniw,opdivu,
                 opotdr,opdivw,oplda,opoutd,opand,opldd,opout,oppush,
                 opcpd,opsbc,opldi,opneg,opind,opcpi,opjar,opotir,
                 opcpl,opini,oprlc,oprld,opdiv,opouti,oprra,opsra,
                 oprrc,oprrd,opscf,opsub,opret,opset,opnop,opinw,
                 oppop,oppcache,opsrl,opdeflef,oprla,opendmac,opexx,
                 opbit,opdi,opei,opxor,opld,opres,oprst,opcp,opadc,
                 opldud,opim,opin,opmepu,opmult,opjp,opmultu,opjr,
                 opex,oprl,opotdrw,opoutdw,opor,opdefbe,opalignv,
                 oprr,opindrw,opotirw,opepuf,opindw,opjaf,opepum,
                 opexts,opdefle,opdeflf,opoutiw,opldw,opoutw,opcpw,
                 opendif,opretb,opdefsf,opsc,opdefdw,opsubw,opextern,
                 optset,opdefhw,optsti,opextl,opepui,opmacro,opldctl,
                 opinclude,opequ,opglobal,opdefqw,opdefvs,opalignp,
                 opif,opdefb,opelse,opelseif,opassm,opdeff,opretil,
                 opbendian,oplendian,opdefps,opmultuw,opdefbef,
                 opcall,opdefw,oplast);

begin
end.
