{*******************************************************************************
*                                                                              *
*                          OPCODE DEFINITION MODULE                            *
*                                                                              *
*                       Copyright (C) 2006 S. A. Moore                         *
*                            All rights reserved                               *
*                                                                              *
* PURPOSE:                                                                     *
*                                                                              *
* Defines the opcodes for this assembler module.                               *
*                                                                              *
* WARNING: *** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY ***         *
*                                                                              *
* This file is generated by hastab from the input file opcode.lab. It defines  *
* the opcodet type, which is an enumerated list of all opcodesin use,          *
* including the assembler directives in use.                                   *
*                                                                              *
* CREATING:                                                                    *
*                                                                              *
* To create this file, run hashtab in this directory.                          *
*                                                                              *
*******************************************************************************}

module opcdef;

{ Opcode type.

  Note: the entries opnull and oplast mark the start and end of the table,
        respectively, and don't represent actual opcodes. }

type  opcodet = (opnull,opcld,opcmc,opcpuid,opcalllf,opcallmf,
                 opendblk,opleaved,opficomd,opcdq,opdaa,opdas,opfidivd,
                 opdecw,opelseif,opfcompd,opfpatan,opalignp,opfabs,
                 opfndisi,opficomp,opfdivrd,opfnclex,opfimuld,opfadds,
                 oplooped,opfidivr,opfcompp,opfsubrd,opfiaddw,opfcomps,
                 opfidivw,opfistpd,opfdivrp,opfsavew,oploopne,opfdivrs,
                 opfsetpm,opfisubw,opjecxzm,opfsubrp,opfchs,opfimulw,
                 opfnstcw,opfyl2xp1,opfistpq,oploopzd,opfcom,opfcoms,
                 opfcomd,opfcomp,opfistpw,opfidiv,opmovsxb,opfeni,
                 opffree,oploopnz,opficomw,opfild,opfnstsw,opmovzxb,
                 opfildq,opfninit,opfist,opfistd,oploopzw,opflds,
                 opfldl,opfldpi,opfldz,opfldcw,opfmuld,opfimul,
                 opfprem,opmovsxw,opfptan,opfrndint,opfsaved,opfscale,
                 opfsin,opfsincos,opmovzxw,opfst,opfsts,opfstps,
                 opfstcw,opfstenvd,opfsub,opfisub,opfisubd,opfsubrs,
                 opfisubr,opfucom,opfucomp,opfucompp,opfwait,opfxam,
                 opfxch,ophlt,opidiv,opidivb,opidivw,opidivd,opbendian,
                 opimul,opimulb,opimuld,opinc,opincb,opincw,opinsb,
                 opinsw,opdefsegl,oplendian,opinsd,opinto,opinvd,
                 opinvlpg,opiret,opiretd,opficompd,opfldenvd,opinclude,
                 opjcxz,opjecxz,opfnsaved,opfidivrd,opfdecstp,opcmpxchg,
                 opjge,opjl,opjle,opjna,opfisubrd,opjnae,oploopned,
                 opjnb,opjnbe,opjnc,opficompw,opfldenvw,opfincstp,
                 opjnge,opjnle,opfnsavew,opfidivrw,opfxtract,opjno,
                 opjnp,opjns,opjpe,opjpo,opfisubrw,opjas,opfrstord,
                 opjaes,oploopnzd,opjbs,opjbes,opjcs,opjgs,opjges,
                 opjls,opfstenvw,opjles,opjnas,opjnbs,opjnbes,opjncs,
                 opjnes,opjnges,opjnls,opjnles,opfrstorw,opjnos,
                 oploopnzw,opjps,opjpes,opjam,opjaem,opjbm,opjbem,
                 opjcm,opjem,opjgm,opjgem,opjlm,opjnbm,opjncm,opjnem,
                 opjngm,opjngem,opjnlm,opjnlem,opjnom,opjnzm,opjpm,
                 opjpem,opjpom,opjael,opjbl,opjbel,opjcl,opjel,
                 opja,opjb,opjc,opjzl,opje,opjgl,opjg,opjgel,opjll,
                 opjlel,opjnal,opbt,opin,opes,opjo,opjp,opm86,opjnbl,
                 opjs,opjnbel,opjncl,opjnel,opor,opjngl,opjngel,
                 opjz,opjnll,opss,opjnlel,opjnol,opjnpl,opjnsl,
                 opjnzl,opjpl,opjpel,opjpol,opjsl,opjmp,opjmps,
                 opjmpm,opjmpl,opjmpf,opjmpmf,opjmplf,oplar,oplds,
                 oples,oplfs,oplgs,oplss,opfnstenvd,oplea,opleave,
                 opleavew,oplgdtw,oplgdtd,oplidtw,oplidtd,oplldt,
                 oplock,oplodsb,oplodsw,oplodsd,oploop,oploopd,
                 opm186,opm286,opm386,opm486,opfnstenvw,oploope,
                 oploopew,oploopnew,oplsl,opltr,opmov,opmovb,opmovd,
                 opcmpxchg8b,opmovsb,opmovsd,opmulb,opmulw,opmuld,
                 opneg,opnegb,opnegw,opnegd,opaaa,opnop,opnot,opaad,
                 opnotb,opadc,opadd,opnotd,oporb,opdec,opord,opout,
                 opaam,opjae,opjbe,opclc,opand,opoutsb,opaas,opfld,
                 opjal,opcli,opbtc,opbtd,opbsf,opcbw,opjne,opcwd,
                 opjng,opcmp,oprcl,opjes,opdiv,opjnl,opjol,opjom,
                 opbsr,opbtr,opbts,opjsm,opint,opjos,opbtw,opmul,
                 oppop,opjss,opjzm,opjnz,opror,opoutsw,oppopd,oppopa,
                 opjzs,oporw,opstr,oppopad,oppopf,oppopfd,oppush,
                 oppushb,oppushw,oppushd,oppusha,oppushad,oppushf,
                 oppushfd,oprclb,oprclw,opfld1,oprcld,oprcr,oprcrb,
                 oprcrw,oprcrd,oprol,oprolb,oprold,oprorb,oprord,
                 oprep,oprepe,oprepz,oprepne,oprepnz,opret,opretf,
                 oprsm,opsahf,opsal,opsalb,opsalw,opsald,opsar,
                 opsarb,opsarw,opsard,opshl,opshlb,opshlw,opshld,
                 opshr,opshrb,opshrw,opadcb,opaddb,opadcd,opaddd,
                 opdecb,opfadd,opdecd,opdefb,opshrd,opsbb,opsbbw,
                 opandb,opsbbd,opandd,opfbld,opsbbb,opfldd,oplahf,
                 opcall,opbtcd,opincd,opadcw,opaddw,opxadd,opcmpb,
                 opcwde,opcmpd,opdivb,opjnam,opdivd,opjlem,opfdiv,
                 opandw,opfcos,opbtrd,opbtsd,opf2xm1,oparpl,opbtcw,
                 opfstd,opjngs,opfnop,opfmul,opjnpm,opclts,opcmpw,
                 opjnsm,opscasb,opdivw,opjnps,opjpos,opfstp,opjnss,
                 opbtrw,opbtsw,opftst,opscasw,oplmsw,oprolw,opjnzs,
                 oppopw,opscasd,opnotw,opmovw,oprorw,opseta,opsetae,
                 opsetb,opsetc,opsete,opxorw,opsetg,opsetge,opsetl,
                 opsetle,opsetna,opsetnae,opsetnb,opsetnbe,opsetnc,
                 opsetne,opsetng,opsetnge,opsetnl,opsetnle,opsetno,
                 opsetnp,opsetns,opsetnz,opseto,opsetp,opsetpe,
                 opsets,opsetz,opsgdtw,opsgdtd,opsidtw,opsidtd,
                 opshldw,opshldd,opshrdw,opshrdd,opsldt,opsmsw,
                 opstc,opfaddd,opstd,opfyl2x,opdefbe,opsti,opfiadd,
                 opstosb,opstosd,opsub,opsubb,opsubw,opsubd,opfaddp,
                 opdefle,opdeflf,opcallf,opfildd,optest,optestb,
                 opendif,optestw,opcalll,opcallm,opjnael,opjnaem,
                 opjnbem,opfdivd,opficom,opfdisi,opfneni,opjnaes,
                 opfclex,opsetbe,opfsubd,opcmpsb,opfildw,opcmpsd,
                 opbound,opfdivp,opfinit,opfdivr,opfdivs,opbswap,
                 openter,opfbstp,opfsubp,opfstpd,opfsubr,opfsubs,
                 opfmulp,optestd,opfistp,opfmuls,oprdmsr,opfstpl,
                 opcmpsw,opsetpo,opjcxzm,opfistw,opimulw,opoutsd,
                 opfsqrt,oploopw,opverr,opverw,oploopz,opwait,opwbinvd,
                 opfstsw,opwrmsr,opfldl2e,opxchg,opfldlg2,opmovsw,
                 opmovsx,opxlatb,opxor,opstosw,opxorb,opfldln2,
                 opxord,opmovzx,opcs,opds,opfs,opfldl2t,opgs,oplarge,
                 opfprem1,opsmall,opfloat,opnfloat,opm586,opmacro,
                 opequ,opsetequ,opglobal,opextern,opalignv,opif,
                 opelse,opassm,opblock,opprint,operror,opfiaddd,
                 opstop,opdefps,opdefvs,opdefbef,opdeff,opdefsf,
                 opdefw,opdefhw,opdefdw,opdeflef,opdefqw,opendmac,
                 opdefseg,opdefsegm,oplast);

begin
end.
