!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!                                                                             !
!                           8051 ASSEMBLER TEST FILE                          !
!                                                                             !
! Contains all of the 8051 operations possible, in opcode numerical order.    !
! Listing in this way has two advantages. One, it is easier to look up by     !
! opcode, and two, it can be sorted into alphabetical order, whereas the      !
! converse is not possible.                                                   !
! To check proper assembler operation, this file is assembled, a listing      !
! containing all generated code is made, and the result hand checked, or      !
! compared to a previous file.                                                !
!                                                                             !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

        nop
        ljmp    $9854
        rr a
        inc     a
        inc     $00
        inc     @r0
        inc     @r1
        inc     r0
        inc     r1
        inc     r2
        inc     r3
        inc     r4
        inc     r5
        inc     r6
        inc     r7
        jbc     $00,_
        lcall   $6543
        rrc a
        dec     a
        dec     $00
        dec     @r0
        dec     @r1
        dec     r0
        dec     r1
        dec     r2
        dec     r3
        dec     r4
        dec     r5
        dec     r6
        dec     r7
        jb      $00,_
        ret
        rl a
        add     a,#$ff
        add     a,$ff
        add     a,@r0
        add     a,@r1
        add     a,r0         
        add     a,r1    
        add     a,r2
        add     a,r3
        add     a,r4
        add     a,r5
        add     a,r6
        add     a,r7
        jnb     $00,_
        acall   $123
        reti
        rlc a
        addc    a,#$ff
        addc    a,$ff
        addc    a,@r0
        addc    a,@r1
        addc    a,r0
        addc    a,r1
        addc    a,r2
        addc    a,r3
        addc    a,r4
        addc    a,r5
        addc    a,r6
        addc    a,r7
        jc      _
        orl     $00,a
        orl     $00,#$ff
        orl     a,#$ff
        orl     a,$ff
        orl     a,@r0
        orl     a,@r1
        orl     a,r0
        orl     a,r1
        orl     a,r2
        orl     a,r3
        orl     a,r4
        orl     a,r5
        orl     a,r6
        orl     a,r7
        jnc     _
        anl     $00,a
        anl     $ff,a
        anl     $00,#$ff
        anl     $ff,#$ff
        anl     a,#$ff
        anl     a,$ff
        anl     a,@r0
        anl     a,@r1
        anl     a,r0
        anl     a,r1
        anl     a,r2
        anl     a,r3
        anl     a,r4
        anl     a,r5
        anl     a,r6
        anl     a,r7
        jz      _
        xrl     $00,a
        xrl     $00,#$ff
        xrl     a,#$ff
        xrl     a,$ff
        xrl     a,@r0
        xrl     a,@r1
        xrl     a,r0
        xrl     a,r1
        xrl     a,r2
        xrl     a,r3
        xrl     a,r4
        xrl     a,r5
        xrl     a,r6
        xrl     a,r7
        jnz     _
        orl     c,$ff
        jmp     @a+dptr
        mov     a,#$00
        mov     $00,#$00
        mov     @r0,#$00
        mov     @r1,#$00
        mov     r1,#$00
        mov     r2,#$00
        mov     r3,#$00
        mov     r4,#$00
        mov     r5,#$00
        mov     r6,#$00
        mov     r7,#$00
        sjmp    _
        ajmp    $456
        anl     c,$ff
        movc    a,@a+pc
        div     ab
        mov     $00,$00
        mov     $00,@r0
        mov     $00,@r1
        mov     $00,r0
        mov     $00,r1
        mov     $00,r2
        mov     $00,r3
        mov     $00,r4
        mov     $00,r5
        mov     $00,r6
        mov     $00,r7
        mov     dptr,#$00ff
        mov     $00,c
        movc    a,@a+dptr
        subb    a,#$ff
        subb    a,$ff
        subb    a,@r0
        subb    a,@r1
        subb    a,r0       
        subb    a,r1       
        subb    a,r2
        subb    a,r3
        subb    a,r4
        subb    a,r5
        subb    a,r6
        subb    a,r7
        orl     c,/$ff
        mov     c,$00
        inc     dptr
        mul     ab
        mov     @r0,$00
        mov     @r1,$00
        mov     r0,$00
        mov     r1,$00
        mov     r2,$00
        mov     r3,$00
        mov     r4,$00
        mov     r5,$00
        mov     r6,$00
        mov     r7,$00
        anl     c,/$ff
        cpl     $00
        cpl     c
        cjne    a,#$00,_
        cjne    a,$00,_
        cjne    @r0,#$00,_
        cjne    @r1,#$ff,_
        cjne    r0,#$00,_
        cjne    r1,#$12,_
        cjne    r2,#$34,_
        cjne    r3,#$56,_
        cjne    r4,#$78,_
        cjne    r5,#$91,_
        cjne    r6,#$23,_
        cjne    r7,#$ff,_
        push    $00
        clr     $00
        clr     c
        swap    a
        xch     a,$00
        xch     a,@r0
        xch     a,@r1
        xch     a,r0
        xch     a,r1
        xch     a,r2
        xch     a,r3
        xch     a,r4
        xch     a,r5
        xch     a,r6
        xch     a,r7
        pop     $00
        setb    $ff
        setb    c
        da      a
        djnz    $00,_
        xchd    a,@r0
        xchd    a,@r1
        djnz    r0,_
        djnz    r1,_
        djnz    r2,_
        djnz    r3,_
        djnz    r4,_
        djnz    r5,_
        djnz    r6,_
        djnz    r7,_
        movx    a,@dptr
        movx    a,@r0
        movx    a,@r1
        clr     a
        mov     a,$00
        mov     a,@r0
        mov     a,@r1
        mov     a,r0
        mov     a,r1
        mov     a,r2
        mov     a,r3
        mov     a,r4
        mov     a,r5
        mov     a,r6
        mov     a,r7
        movx    @dptr,a
        movx    @r0,a
        movx    @r1,a
        cpl     a
        mov     $00,a
        mov     @r0,a
        mov     @r1,a
        mov     r0,a
        mov     r1,a
        mov     r2,a
        mov     r3,a
        mov     r4,a
        mov     r5,a
        mov     r6,a
        mov     r7,a
