{*******************************************************************************
*                                                                              *
*                          OPCODE DEFINITION MODULE                            *
*                                                                              *
*                       Copyright (C) 2006 S. A. Moore                         *
*                            All rights reserved                               *
*                                                                              *
* PURPOSE:                                                                     *
*                                                                              *
* Defines the opcodes for this assembler module.                               *
*                                                                              *
* WARNING: *** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY ***         *
*                                                                              *
* This file is generated by hastab from the input file opcode.lab. It defines  *
* the opcodet type, which is an enumerated list of all opcodesin use,          *
* including the assembler directives in use.                                   *
*                                                                              *
* CREATING:                                                                    *
*                                                                              *
* To create this file, run hashtab in this directory.                          *
*                                                                              *
*******************************************************************************}

module opcdef;

{ Opcode type.

  Note: the entries opnull and oplast mark the start and end of the table,
        respectively, and don't represent actual opcodes. }

type  opcodet = (opnull,opdjnz,oplendian,opdeflf,oprl,opsjmp,opadd,
                 opda,opendif,opdec,opjz,oppush,opjbc,opdiv,opjc,
                 opjnb,opdefhw,opjnc,oplcall,opmov,opmacro,opmovx,
                 oporl,opinc,opanl,opdefqw,opdefvs,opreti,opcpl,
                 oprlc,opclr,opdeflef,opaddc,opendmac,oprr,oprrc,
                 opjmp,opdefb,opswap,opxch,opret,opdeff,opnop,opmul,
                 oppop,opxchd,opinclude,opjnz,opequ,opelseif,opglobal,
                 opxrl,opcjne,opextern,opalignp,opassm,opdefps,
                 opdefbe,opalignv,opjb,opajmp,opelse,opif,opdefle,
                 opsubb,opbendian,opsetb,opdefbef,opdefsf,opdefw,
                 opdefdw,opljmp,opacall,opmovc,oplast);

begin
end.
