{*******************************************************************************
*                                                                              *
*                         OPCODE INITIALIZATION MODULE                         *
*                                                                              *
*                       Copyright (C) 2006 S. A. Moore                         *
*                            All rights reserved                               *
*                                                                              *
* PURPOSE:                                                                     *
*                                                                              *
* Defines the opcodes for this assembler module.                               *
*                                                                              *
* WARNING: *** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY ***         *
*                                                                              *
* This file is generated by hastab from the input file opcode.lab. It defines  *
* the resini procedure, that initializes the reserved word table.              *
*                                                                              *
* CREATING:                                                                    *
*                                                                              *
* To create this file, run hashtab in this directory.                          *
*                                                                              *
*******************************************************************************}

module opcini;

uses utl,    { assembly support routines }
     opcdef, { opcode definition }
     macdef; { machine specific definition }

var ressym: restab; { reserved symbols table }

{*******************************************************************************
                                                                                
Initalize reserved word table                                                   
                                                                                
The reserved word table is an array of records, with each record containing a   
label, and a entry chain. The label is the actual reserved word itself. The     
chain is an index into the reserved word table itself. Each position (index) in 
the reserved word table corresponds to a 'hash' value for a given label. The    
hash value is a random function derived for the label that gives some level     
(typ > 90%) of 'uniqueness' for a given label (see the 'hash' routine for       
details of the process). Each 'prime' label occupys the entry cooresponding to  
it's hash value (a prime entry means that it is the first label for the hash    
value to be placed). Duplicate entrys are placed in locations that have no      
prime label. The chain fields then point to these labels succesively from the   
prime entry, terminated with 0. A lookup is performed by succesively examining  
each label in a chain, starting with the prime label, until a match is found    
or the end of a chain is reached.                                               
                                                                                
This routine sets up the labels and chain fields making up the table. The table 
should already be cleared.                                                      
                                                                                
*******************************************************************************}

procedure resini;

begin

   { labels }

   copy(ressym[opdjnz   ].reslab, 'djnz      ');
   copy(ressym[oplendian].reslab, 'lendian   ');
   copy(ressym[opdeflf  ].reslab, 'deflf     ');
   copy(ressym[oprl     ].reslab, 'rl        ');
   copy(ressym[opsjmp   ].reslab, 'sjmp      ');
   copy(ressym[opadd    ].reslab, 'add       ');
   copy(ressym[opda     ].reslab, 'da        ');
   copy(ressym[opendif  ].reslab, 'endif     ');
   copy(ressym[opdec    ].reslab, 'dec       ');
   copy(ressym[opjz     ].reslab, 'jz        ');
   copy(ressym[oppush   ].reslab, 'push      ');
   copy(ressym[opjbc    ].reslab, 'jbc       ');
   copy(ressym[opdiv    ].reslab, 'div       ');
   copy(ressym[opjc     ].reslab, 'jc        ');
   copy(ressym[opjnb    ].reslab, 'jnb       ');
   copy(ressym[opdefhw  ].reslab, 'defhw     ');
   copy(ressym[opjnc    ].reslab, 'jnc       ');
   copy(ressym[oplcall  ].reslab, 'lcall     ');
   copy(ressym[opmov    ].reslab, 'mov       ');
   copy(ressym[opmacro  ].reslab, 'macro     ');
   copy(ressym[opmovx   ].reslab, 'movx      ');
   copy(ressym[oporl    ].reslab, 'orl       ');
   copy(ressym[opinc    ].reslab, 'inc       ');
   copy(ressym[opanl    ].reslab, 'anl       ');
   copy(ressym[opdefqw  ].reslab, 'defqw     ');
   copy(ressym[opdefvs  ].reslab, 'defvs     ');
   copy(ressym[opreti   ].reslab, 'reti      ');
   copy(ressym[opcpl    ].reslab, 'cpl       ');
   copy(ressym[oprlc    ].reslab, 'rlc       ');
   copy(ressym[opclr    ].reslab, 'clr       ');
   copy(ressym[opdeflef ].reslab, 'deflef    ');
   copy(ressym[opaddc   ].reslab, 'addc      ');
   copy(ressym[opendmac ].reslab, 'endmac    ');
   copy(ressym[oprr     ].reslab, 'rr        ');
   copy(ressym[oprrc    ].reslab, 'rrc       ');
   copy(ressym[opjmp    ].reslab, 'jmp       ');
   copy(ressym[opdefb   ].reslab, 'defb      ');
   copy(ressym[opswap   ].reslab, 'swap      ');
   copy(ressym[opxch    ].reslab, 'xch       ');
   copy(ressym[opret    ].reslab, 'ret       ');
   copy(ressym[opdeff   ].reslab, 'deff      ');
   copy(ressym[opnop    ].reslab, 'nop       ');
   copy(ressym[opmul    ].reslab, 'mul       ');
   copy(ressym[oppop    ].reslab, 'pop       ');
   copy(ressym[opxchd   ].reslab, 'xchd      ');
   copy(ressym[opinclude].reslab, 'include   ');
   copy(ressym[opjnz    ].reslab, 'jnz       ');
   copy(ressym[opequ    ].reslab, 'equ       ');
   copy(ressym[opelseif ].reslab, 'elseif    ');
   copy(ressym[opglobal ].reslab, 'global    ');
   copy(ressym[opxrl    ].reslab, 'xrl       ');
   copy(ressym[opcjne   ].reslab, 'cjne      ');
   copy(ressym[opextern ].reslab, 'extern    ');
   copy(ressym[opalignp ].reslab, 'alignp    ');
   copy(ressym[opassm   ].reslab, 'assm      ');
   copy(ressym[opdefps  ].reslab, 'defps     ');
   copy(ressym[opdefbe  ].reslab, 'defbe     ');
   copy(ressym[opalignv ].reslab, 'alignv    ');
   copy(ressym[opjb     ].reslab, 'jb        ');
   copy(ressym[opajmp   ].reslab, 'ajmp      ');
   copy(ressym[opelse   ].reslab, 'else      ');
   copy(ressym[opif     ].reslab, 'if        ');
   copy(ressym[opdefle  ].reslab, 'defle     ');
   copy(ressym[opsubb   ].reslab, 'subb      ');
   copy(ressym[opbendian].reslab, 'bendian   ');
   copy(ressym[opsetb   ].reslab, 'setb      ');
   copy(ressym[opdefbef ].reslab, 'defbef    ');
   copy(ressym[opdefsf  ].reslab, 'defsf     ');
   copy(ressym[opdefw   ].reslab, 'defw      ');
   copy(ressym[opdefdw  ].reslab, 'defdw     ');
   copy(ressym[opljmp   ].reslab, 'ljmp      ');
   copy(ressym[opacall  ].reslab, 'acall     ');
   copy(ressym[opmovc   ].reslab, 'movc      ');

   { chains }

   ressym[oplendian].reschn := opdefle;
   ressym[opadd    ].reschn := opswap;
   ressym[opda     ].reschn := opalignp;
   ressym[opjz     ].reschn := oplcall;
   ressym[oppush   ].reschn := opinclude;
   ressym[opjbc    ].reschn := opdefdw;
   ressym[opdiv    ].reschn := opxch;
   ressym[oplcall  ].reschn := oprr;
   ressym[opmacro  ].reschn := opdefps;
   ressym[opmovx   ].reschn := opdefbef;
   ressym[oporl    ].reschn := opglobal;
   ressym[opinc    ].reschn := opjnb;
   ressym[opanl    ].reschn := opjnc;
   ressym[opreti   ].reschn := opassm;
   ressym[opclr    ].reschn := oprlc;
   ressym[opaddc   ].reschn := opdiv;
   ressym[oprr     ].reschn := opdefsf;
   ressym[opjmp    ].reschn := oprrc;
   ressym[opswap   ].reschn := opextern;
   ressym[opret    ].reschn := opequ;
   ressym[opnop    ].reschn := oporl;
   ressym[opjnz    ].reschn := opmov;
   ressym[opcjne   ].reschn := opda;
   ressym[opalignv ].reschn := opdefw;
   ressym[opjb     ].reschn := opxchd;
   ressym[opajmp   ].reschn := opjc;
   ressym[opbendian].reschn := opdefbe;
   ressym[opacall  ].reschn := opreti;

end;

begin
end.
