{*******************************************************************************
*                                                                              *
*                          OPCODE DEFINITION MODULE                            *
*                                                                              *
*                       Copyright (C) 2006 S. A. Moore                         *
*                            All rights reserved                               *
*                                                                              *
* PURPOSE:                                                                     *
*                                                                              *
* Defines the opcodes for this assembler module.                               *
*                                                                              *
* WARNING: *** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY ***         *
*                                                                              *
* This file is generated by hastab from the input file opcode.lab. It defines  *
* the opcodet type, which is an enumerated list of all opcodesin use,          *
* including the assembler directives in use.                                   *
*                                                                              *
* CREATING:                                                                    *
*                                                                              *
* To create this file, run hashtab in this directory.                          *
*                                                                              *
*******************************************************************************}

module opcdef;

{ Opcode type.

  Note: the entries opnull and oplast mark the start and end of the table,
        respectively, and don't represent actual opcodes. }

type  opcodet = (opnull,opdec,opcpi,ophalt,opsra,oprrd,opret,opdaa,
                 opnop,opadc,opadd,opinc,opsla,opccf,opdi,opei,
                 opif,opld,opdefb,opretn,opand,opldd,opdeff,opim,
                 opcpd,opsbc,opldi,opneg,opind,opcall,opex,oprl,
                 opcpl,opini,oprlc,oprlca,oprld,oprr,oprra,oplddr,
                 oprrc,oprrca,opcpdr,opsub,opldir,opset,opindr,
                 opcpir,oppop,opscf,opsrl,opinir,oprla,opreti,opexx,
                 opdjnz,opdefqw,opout,opotdr,opbit,opalignp,opoutd,
                 opres,opotir,opcp,oppush,opouti,opxor,opin,opinclude,
                 oprst,opjp,opjr,opor,opmacro,opendmac,opequ,opglobal,
                 opalignv,opelse,opelseif,opendif,opassm,opbendian,
                 oplendian,opdefps,opdefvs,opextern,opdefbe,opdefle,
                 opdefbef,opdeflef,opdefsf,opdeflf,opdefw,opdefhw,
                 opdefdw,oplast);

begin
end.
