{*******************************************************************************
*                                                                              *
*                          OPCODE DEFINITION MODULE                            *
*                                                                              *
*                       Copyright (C) 2006 S. A. Moore                         *
*                            All rights reserved                               *
*                                                                              *
* PURPOSE:                                                                     *
*                                                                              *
* Defines the opcodes for this assembler module.                               *
*                                                                              *
* WARNING: *** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY ***         *
*                                                                              *
* This file is generated by hastab from the input file opcode.lab. It defines  *
* the opcodet type, which is an enumerated list of all opcodesin use,          *
* including the assembler directives in use.                                   *
*                                                                              *
* CREATING:                                                                    *
*                                                                              *
* To create this file, run hashtab in this directory.                          *
*                                                                              *
*******************************************************************************}

module opcdef;

{ Opcode type.

  Note: the entries opnull and oplast mark the start and end of the table,
        respectively, and don't represent actual opcodes. }

type  opcodet = (opnull,opxri,opsub,opjz,oppush,oppop,opout,oprst,
                 oprnz,opdad,opinx,oprz,opdcx,opxchg,opxthl,oplxi,
                 opani,opori,oplda,oplhld,opjmp,opjc,opjnz,opjm,
                 opjp,opjpe,opjpo,opcc,opcnz,opcm,opcpe,opcpo,opret,
                 oprc,oprp,oprpe,oprpo,opei,opdi,opin,opdefbef,
                 ophlt,opmacro,opequ,opbendian,opsetequ,opextern,
                 opalignp,opalignv,opif,opdeflef,opdefbe,opendmac,
                 opelse,oplendian,opassm,opblock,opprint,operror,
                 opstop,opendblk,opglobal,opdeflf,opinclude,opdefb,
                 opdefps,opdefvs,opendif,opelseif,opdaa,opdefle,
                 opadc,opadd,opdeff,opcall,opdefhw,opaci,opadi,
                 opdefsf,opana,opcma,opdefdw,opcmc,opcnc,opdefw,
                 oppchl,opsbb,opldax,opdcr,opshld,opjnc,opcpi,opdefqw,
                 opsbi,opral,opcmp,oprlc,opora,oprnc,opcp,oprar,
                 opsphl,oprrc,opsta,opinr,opstc,opxra,opmvi,opnop,
                 opcz,opstax,oprm,opsui,opmov,oplast);

begin
end.
